// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectOfNguyenTrungKien.Data;

#nullable disable

namespace ProjectOfNguyenTrungKien.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230528092442_Alter_Table_Products_And_Categories_Update_Field_Date_Updated_Time_Updated")]
    partial class Alter_Table_Products_And_Categories_Update_Field_Date_Updated_Time_Updated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectOfNguyenTrungKien.Data.Categories", b =>
                {
                    b.Property<Guid>("CodeCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Time_Created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time_Updated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodeCategory");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ProjectOfNguyenTrungKien.Data.Products", b =>
                {
                    b.Property<Guid>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CodeCategory")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Date_Created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Updated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Discount")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Time_Created")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time_Updated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("CodeCategory");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProjectOfNguyenTrungKien.Data.Products", b =>
                {
                    b.HasOne("ProjectOfNguyenTrungKien.Data.Categories", "Categories")
                        .WithMany("Products")
                        .HasForeignKey("CodeCategory");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("ProjectOfNguyenTrungKien.Data.Categories", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
